require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/OrAssignment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
